version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-crud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - php-crud-01-2025-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - php-crud-01-2025-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "82:82"
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - php-crud-01-2025-network

volumes:
  mysql_data:

networks:
  php-crud-01-2025-network:
    driver: bridge